name: flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  device_preview: 1.2.0
  flutter_staggered_grid_view: ^0.6.1
  image_picker: ^0.8.7
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
